name: frontend-test

on: push

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install missing peer dependency
        run: npm install vite@^4.1.0-beta.0 --save-dev

      - name: Install dependencies
        run: npm install

      - name: Build and test
        run: npm run dev && exit